version: '3'

services:
  web:
    build: .
    command: ["sh", "-c", "sleep 10 && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - my-postgres

  my-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    
